### ISSUE TITLE
Publish pyHydrabus on PyPI

### ISSUE THREAD

**Issue by ghecko** [hydrabus/hydrafw#103]
Hi,

It would be relevant to publish pyHydrabus on Pypi.

**Comment by Baldanos** [comment]
Hi !

pyHydrabus is still under development and there might be possible API changes.
As soon as the module is stable enough (ie all the current features are tested) I'll publish it on pypi.

Feel free to comment this issue with things you've tested and/or want to see modified.

**Comment by ghecko** [comment]
Hi,

I didn't see your response before.
Great, I will probably create some pull requests to add new features and change asserts' call (If no working issue is induced) as soon as possible, are you OK with this?

**Comment by Baldanos** [comment]
Sure ! 
Feel free to send us pull requests.

**Comment by Baldanos** [comment]
pyHydrabus has been published on Pypi : https://pypi.org/project/pyHydrabus/
