### ISSUE TITLE
Can't use HydraFW with OpenOCD in SWD mode

### ISSUE THREAD

**Issue by elektrischermoench** [hydrabus/hydrafw#129]
I always fail to get HydraFW newest version up and running with OpenOCD:

% openocd -f hydrabus_openocd.cfg -d
...
Debug: 71 12 semihosting_common.c:99 semihosting_common_init():  
Debug: 72 114 buspirate.c:1000 buspirate_bbio_enable(): Entering binary mode, that is RAW1
Debug: 73 114 buspirate.c:1225 buspirate_serial_write(): size = 20 ret = 20
Debug: 74 114 buspirate.c:1287 buspirate_print_buffer(): 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Debug: 75 114 buspirate.c:1293 buspirate_print_buffer(): 00 00 00 00 
Debug: 76 10128 buspirate.c:1257 buspirate_serial_read(): should have read = 4 actual size = 0
Error: 77 10128 buspirate.c:1261 buspirate_serial_read(): Error reading data
Error: 78 10128 buspirate.c:1009 buspirate_bbio_enable(): Buspirate error. Is binary/OpenOCD support enabled?

Reading from my Hydrabus doesn't work. Any ideas how I can fix the issue?
Of course my Hydrabus is connected to an actual device via 2-wire SWD connection.

**Comment by elektrischermoench** [comment]
> show version
Invalid command.
> show system
HydraFW (HydraBus) v0.10-47-ge1c55ec 2021-02-01
sysTime: 0x00022d42.
cyclecounter: 0x02663c31 cycles.
cyclecounter64: 0x0000000002663c44 cycles.
10ms delay: 1680026 cycles.

MCU Info
DBGMCU_IDCODE:0x10016413
CPUID:        0x410FC241
Flash UID:    0x25001C 0x32334719 0x38333637
Flash Size:   1024KB

Kernel:       ChibiOS 5.1.0
Compiler:     GCC 9.3.1 20200408 (release)
Architecture: ARMv7E-M
Core Variant: Cortex-M4F
Port Info:    Advanced kernel mode
Platform:     STM32F405 High Performance with DSP and FPU
Board:        HydraBus 1.0
Build time:   Mar  8 2021 - 14:17:04
> 




cfg:

# This configuration allows to use Hydrabus as a SWD debugger.
#
# SWDCLK - PB3
# SWDIO  - PB4
# nRST   - PC4
#
# http://www.hydrabus.com

source [find interface/buspirate.cfg]
# Change port accordingly
buspirate_port /dev/tty.usbmodem14201 
transport select swd

# Change the target accordingly
#source [find target/cc32xx.cfg]
source [find target/cc32xx.cfg]
adapter_khz 10
# If connect-under-reset is needed
reset_config srst_nogate connect_assert_srst


running as root didn't change the behaviour.

**Comment by elektrischermoench** [comment]
when i configure the frequency to 10 in the console before it seems to work better but still fails:

output of Hydrabus shell:
```shell
twowire1> frequency 10
twowire1> 1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO1BBIO
```

corresponding output of OpenOCD:
```shell
Debug: 74 106 buspirate.c:1000 buspirate_bbio_enable(): Entering binary mode, that is RAW1
Debug: 75 106 buspirate.c:1225 buspirate_serial_write(): size = 20 ret = 20
Debug: 76 106 buspirate.c:1287 buspirate_print_buffer(): 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Debug: 77 106 buspirate.c:1293 buspirate_print_buffer(): 00 00 00 00 
Debug: 78 126 buspirate.c:1257 buspirate_serial_read(): should have read = 4 actual size = 4
Debug: 79 126 buspirate.c:1293 buspirate_print_buffer(): 42 42 49 4f 
Debug: 80 10129 buspirate.c:1257 buspirate_serial_read(): should have read = 1 actual size = 0
Error: 81 10129 buspirate.c:1261 buspirate_serial_read(): Error reading data
Error: 82 10129 buspirate.c:1016 buspirate_bbio_enable(): Buspirate did not answer correctly! Do you have correct firmware?
```

**Comment by elektrischermoench** [comment]
the debug output is very long but here some errors I found in it:

```shell
bug: 2646 638 buspirate.c:1536 buspirate_swd_run_queue(): SWD queue return value: 07
Error: 2647 639 adi_v5_swd.c:144 swd_connect(): Error connecting DP: cannot read IDR
Debug: 2648 639 command.c:629 run_command(): Command 'dap init' failed with error code 7
User : 2649 639 command.c:694 command_run_line(): 
Debug: 2650 639 command.c:629 run_command(): Command 'init' failed with error code -4
User : 2651 639 command.c:694 command_run_line(): 
Debug: 2652 639 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas
Debug: 2653 639 buspirate.c:1324 buspirate_swd_switch_seq(): SWD-to-JTAG
Debug: 2654 639 buspirate.c:1225 buspirate_serial_write(): size = 11 ret = 11
```

**Comment by Baldanos** [comment]
The openOCD SWD interface seems to work.
Now the problem seems to be about the target device. It seems openOCD cannot access the target using SWD.

From what you wrote, there seems to be data on the SWDIO pin, but it might be a wrong pin as well.

It's hard to tell you more since I cannot see your target, but here are some hints :
 - Make sure you are connected to the right SWD pins (check the target chip datasheet)
 - Verify if you need to assert nRST before connecting, and wire it accordingly (should be connected to PC4 on Hydrabus)
