### ISSUE TITLE
Firmware Flashing

### ISSUE THREAD

**Issue by grng3r** [hydrabus/hydrafw#131]
Hello guys, I don't know if this is the correct place for this, but recently bought HydraBus and have a lot of problems flashing firmware. The board is not recognized by the host either in normal mode or dfu mode, This was attempted on Windows 10, Ubuntu 18.04 and Raspbian on a raspberry pi 3B+.  I have attempted even reverting dfu-util from current version 0.11 from my OS package manager dfu-util  0.8 
The attempts where made with multiple USB cables, ports and docks and each time the result is the same. 
In normal mode when executing command

```
lsub
```
or in dfu mode when executing command

```
dfu-util -l
```
the device is not recognized, it is not even loaded when listing /dev.
Normally I would suppose there is hardware problem, but the board powers up and I get all the expected LEDs blinking, so was thinking that I maybe have some dependancy issued or something.
Your documentation was followed in each case.
Thank you in advance!

**Comment by bvernoux** [comment]
Please follow carefully the Wiki (especially using an external Hub like described):
For Windows:
- https://github.com/hydrabus/hydrafw/wiki/Getting-Started-with-HydraBus-flash-and-use-hydrafw-on-windows

For GNU/Linux:
- https://github.com/hydrabus/hydrafw/wiki/Getting-Started-with-HydraBus-flash-and-use-hydrafw-on-linux

If you have still any issue please provide all details (and where you have bought the HydraBus) and contact: support at hydrabus dot com
