### ISSUE TITLE
1-wire: Use discovered "MAC" addresses, maybe with additional macros?

### ISSUE THREAD

**Issue by jbglaw** [hydrabus/hydrafw#137]
Some of the supported busses have the concept of addressable microcontrollers. For example, I've been looking at the one-wire bus. There is a mechanism to discover all IC addresses (which I hereby reference as "MAC" address in general.)

I suggest to allow the individual `scan` commands to register the (sorted) list of MAC addresses along with just printing them. That would allow to use them in later commands. As an example, I have attached two DS1820 (one-wire temperature sensors) which are (after fixing the `scan` mechanism) properly detected.

To issue a "sample temperature" command, I would have to issue this:

```
[ 0x55 0x10 0x54 0xD0 0xD3 0x00 0x08 0x00 0xA8 0x44
```

- `0x55` = "Match ROM address".
- `0x10 0x54 0xD0 0xD3 0x00 0x08 0x00 0xA8` = MAC address as displayed by the `scan` command.
- `0x44` = device-specific "sample temperature" command, only being executed by the named device.

Insted of placing the whole MAC address manually, I suggest to reference that symbolically:

```
[ 0x55 <1> 0x44
```
That would be `0x55` (= Match ROM address), `<1>` would insert the Number 1 device MAC address, followed by the `0x44` (sample temperature) command. I guess that implementing this generically would be beneficial for other bus/connection types as well.

Additionally, it might be feasible to have macros of some kind. Maybe just a (user-settable) mapping of a short macro name resolving in one or a number of bytes:
```
macro MATCH_ROM 0x55
macro DS1820_SAMPLE_TEMPERATURE 0x44
macro DS1820_READ_TEMPERATURE 0xbe

[ MATCH_ROM <1> DS1820_SAMPLE_TEMPERATURE
[ MATCH_ROM <1> DS1820_READ_TEMPERATURE
```

**Comment by bvernoux** [comment]
Macro are not planned to be added in HydraBus firmware as it can be done on PC side with I2C BBIO (see https://github.com/hydrabus/hydrafw/wiki/HydraFW-Binary-I2C-mode-guide) with python or other language ...
