### ISSUE TITLE
protocole iso*/ k-line

### ISSUE THREAD

**Issue by Alfa16bravo** [hydrabus/hydrafw#145]
hello, would it be possible to add the k-line protocol? THANKS

**Comment by Alfa16bravo** [comment]
L9637D converts the uart pin to k-line and modifies the 5v uart to 12v output for k-line and vice versa, I prepared a "board" for this

**Comment by Alfa16bravo** [comment]
hello, I write a code in python using the bbio mode of the hydrabus and the uart mode, the conversions for the kline are done with the l9637d, I plugged my saleae on the rx pin of the l9637d and connected a tool The engine ecu and I are receiving many frames, both ISO 9141 and 14230 are experiencing a 5 baud initialization sequence. The microcontroller should start this initialization by transmitting byte 0x33 to the vehicle at 5 bits per second. The total transmission time for the transmission of byte 0x33 takes approximately 2 seconds. After this initialization, it is expected to continue to communicate at 10k4 baud.For ISO 9141-2 the verhicle ECU will respond with synchronization byte 0x55. After this, the verhicle will respond with key bytes 0x08 and 0x08 or 0x96 and 0x96. The sync byte with key bytes of the verhicle must be acknowledged by the microcontroller by inverting the second key byte. This will end the initialization part of ISO 9141-2.  the first problem is that the hydrabus does not accept such a low baud rate, someone to help me? THANKS

**Comment by bvernoux** [comment]
The only way to support such non standard ultra low baud rate is to use GPIO bit-banging a bit like we do with I2C but adapted for your specific purpose see for example https://github.com/hydrabus/hydrafw/blob/master/src/drv/stm32cube/bsp_i2c_master.c

**Comment by Alfa16bravo** [comment]
arf, i don't know how to code in c

**Comment by bvernoux** [comment]
> arf, i don't know how to code in c

Just to be clear on my side I clearly do not have any time / hardware and interest in such feature so like described before PR is welcome but you are on your own and you should find other interested developer to help you for that or learn by yourself how to do development as everything is open source

**Comment by Alfa16bravo** [comment]
hello, thank you for your answer, I will try to find developers who are interested in helping me create this functionality.

**Comment by bvernoux** [comment]
> hello, thank you for your answer, I will try to find developers who are interested in helping me create this functionality.

Do you have any update about that feature ? (Does this is something you plan to implement in short/mid term or does it is cancelled ?)

**Comment by bvernoux** [comment]
No feedback since lot of time issue closed
