### ISSUE TITLE
BDM NXP (Freescale) bkgd

### ISSUE THREAD

**Issue by Alfa16bravo** [hydrabus/hydrafw#146]
hello, in the near future the bdm protocol could be added? thanks
NXP (Freescale)

**Comment by bvernoux** [comment]
Such feature is not planned and will requires more details to better understand what it is exactly and on which MCU/CPU/Platform it can be used/tested
PR is welcome as always

**Comment by Alfa16bravo** [comment]
hello, I will gather all the necessary information and I will post them. THANKS
