### ISSUE TITLE
HydraNFC add SDM TX/DM1 RX mode to implement custom/advanced Reader/Writer/Emulation [Planned for HydraNFC v2]

### ISSUE THREAD

**Issue by bvernoux** [hydrabus/hydrafw#43]
Work in progress using TI [sloa214 "Using Special Direct Mode With the TRF7970A Feb2015"](http://www.ti.com/general/docs/litabsmultiplefilelist.tsp?literatureNumber=sloa214)
- Direct Mode Transceive => SDM TX then DM1 RX with management of Parity (if enabled)  & CRC (if enabled) 
- Separate mode SDM TX
- Separate mode DM1 RX

This mode is mandatory for ISO14443A non compliant Tag like Mifare Classic ...

**Comment by gibix** [comment]
There is some working progress code for this issue?

**Comment by bvernoux** [comment]
It is always planned with lot of great features for 2017
For information the HydraNFC part will be separated (removed from main hydrafw) and moved to an other repository stay tuned

**Comment by bvernoux** [comment]
This feature is cancelled for HydraNFC v1 but it will be integrated with HydraNFC v2 which use an other chipset much more powerful in all area and have also similar advanced mode for custom Emulation / Reader / Sniffer ...

**Comment by bvernoux** [comment]
Closed
Feature cancelled for HydraNFC v1 but will be supported with HydraNFC v2 with different way to do low level emulation/Advanced Reader/Sniffer
