### ISSUE TITLE
Live sniffing via UART1 at different baud rate

### ISSUE THREAD

**Issue by zhovner** [hydrabus/hydrafw#83]
* I want to use live sniffing but it's unhandy to connect simultaneously 2 usb cables in the same time. Is there any way to get live output via DFU USB port? Maybe with some lag. For now I'm connecting to serial console, then press K3 button, sniff, and then press K4 to see captured data in terminal. Sort of live sniffing :)

* I only have two TTL adapters: CP1201 and Prolific PL2303 which supports a 115200 max baud rate. When I try to use it with hydratool, I always get incorrect data `frame size error resync data`. Do I really need the TTL adapter that support 8.4M baud rate? Or I can change the UART1 baud rate on hydrabus?

**Comment by bvernoux** [comment]
What happen in your case is you try to output lot of data (too much for 115200 or even 2Mbauds serial port) with too slow Serial Port 115200 so you have some data loss at end with frame size error resync data.
It is not possible to do continuous NFC Sniffing at less than 2M bauds (for 106KHz NFC Tag).
Safe value is  8.4Mbauds in order it works even with 424KHz or 848KHz Tag.
It is the same for USB DFU it is too slow and too intrusive as it cost lot of CPU time to use USB with Sniffing in real-time (so some data will be lost) so the only solution so far is to use FTDI interface C232HM-DDHSL-0 interface which allow unique infinite & real-time continuous NFC sniffing

For more details all is explained here
* https://github.com/hydrabus/hydrafw/wiki/HydraFW-HYDRANFC-guide#unique-nfc-sniffer-design
* https://github.com/hydrabus/hydrafw/wiki/HydraFW-HYDRANFC-guide#sniffer-iso14443a-with-unique-hard-real-time-infinite-trace-mode

**Comment by zhovner** [comment]
Okay, I get. 
I would prefer to enable live sniffing mode by pressing some combination of hardware buttons. Maybe possible to bind user script execution to hardware button? For example user put list of command in file on SDcard, and this script runs when specific button pressed.

**Comment by bvernoux** [comment]
You are welcome to create such feature and provide a pull request
