### ISSUE TITLE
[hydrafw uart binary mode] Start echo UART RX doesn't work

### ISSUE THREAD

**Issue by ghecko** [hydrabus/hydrafw#99]
The "echo UART RX" features seems not working, no output is return.
I using the script provided on the documentation to be sure.
By using the bridge mode, the output are correct.

**Comment by Baldanos** [comment]
Hi !

This should be fixed in https://github.com/hydrabus/hydrafw/commit/463bfc5ad230e4a73c32aed6a726dd4c74997364

Can you please update and try again ?

**Comment by ghecko** [comment]
Hi !

Thanks you for your time, it work perfectly now :)
I close this issue !
